spring:
  application:
    name: @project.artifactId@-local
  security:
    user:
      name: i18n
      password: i18n
      roles: i18n, admin

logging:
  level:
    win.doyto.query.core: debug
    org.springframework.security: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
