#激活profile:cloud后, 开启config和eureka
spring:
  cloud:
    config:
      uri: http://config:8888
      discovery:
        enabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka}:8761/eureka/
