spring:
  application:
    name: @project.artifactId@
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:${ENV_HOST}}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}
  redis:
    host: ${REDIS_DEFAULT_HOST:${ENV_HOST}}
    password: ${REDIS_DEFAULT_PASS:redis}
    port: 6379
    pool:
      max-active: 10
      max-wait: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${jdbc.host:localhost}:${jdbc.port:3306}/i18n?autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: ${jdbc.username:i18n}
    password: ${jdbc.password:i18n_pass}
    hikari:
      jdbc-url: ${spring.datasource.url}

mybatis:
  config-location: classpath:mybatis.xml
  executor-type: reuse

logging:
  level:
    root: info
    com.netflix.discovery.shared.resolver.aws: warn

#hystrix 熔断机制
feign.hystrix.enabled: true

doyto:
  domain: host.local
  home-url: http://www.${doyto.domain}
  sso-url: http://sso.${doyto.domain}
  login-url: ${doyto.sso-url}/login?redirect=http://i18n.${doyto.domain}/
  failure-url: ${doyto.sso-url}/login?error
  remember-me-token: doyto_token
  remember-me-cookie: doyto_account
  baidu:
    appid: 20170417000044993
    securityKey: VaF807U3s7X6ZpRkcThL
