spring:
  application:
    name: @project.artifactId@
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:${ENV_HOST}}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}
  redis:
    host: ${REDIS_DEFAULT_HOST:${ENV_HOST}}
    password: ${REDIS_DEFAULT_PASS:redis}
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 5
  cloud:
    config:
      enabled: true

spring.cloud.refresh.refreshable: none
spring.jmx.enabled: false

mybatis:
  config-location: classpath:mybatis.xml
  executor-type: reuse

logging:
  level:
    root: info
    com.netflix.discovery.shared.resolver.aws: warn
    org.springframework.boot.devtools.autoconfigure: warn

#hystrix 熔断机制
feign.hystrix.enabled: true

doyto:
  domain: host.local
  home-url: http://www.${doyto.domain}
  sso-url: http://sso.${doyto.domain}
  login-url: ${doyto.sso-url}/login?redirect=http://i18n.${doyto.domain}/
  failure-url: ${doyto.sso-url}/login?error
  remember-me-token: doyto_token
  remember-me-cookie: doyto_account
  baidu:
    appid: 20170417000044993
    securityKey: VaF807U3s7X6ZpRkcThL
